#############################################################################
# Makefile for building: COVID_SIM_UI.app/Contents/MacOS/COVID_SIM_UI
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  COVID_SIM_UI.pro
# Template: app
# Command: /Users/nyuad/Qt/5.15.2/clang_64/bin/qmake -o COVID_SIM_UI.xcodeproj/project.pbxproj COVID_SIM_UI.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/nyuad/Qt/5.15.2/clang_64/bin/moc
UIC       = /Users/nyuad/Qt/5.15.2/clang_64/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
INCPATH       = -I. -Ilibs/Release -Iheader -IInclude -I../../../Qt/5.15.2/clang_64/lib/QtPrintSupport.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtSql.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.15.2/clang_64/mkspecs/macx-clang -F/Users/nyuad/Qt/5.15.2/clang_64/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_predefs.h moc_qcustomplot.cpp moc_mainwindow.cpp moc_worker.cpp ui_mainwindow.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h ../../../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qcustomplot.cpp moc_mainwindow.cpp moc_worker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qcustomplot.cpp moc_mainwindow.cpp moc_worker.cpp
moc_qcustomplot.cpp: header/qcustomplot.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		moc_predefs.h \
		../../../Qt/5.15.2/clang_64/bin/moc
	/Users/nyuad/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/moc_predefs.h -I/Users/nyuad/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/libs/Release -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/header -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/Include -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtSql.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/nyuad/Qt/5.15.2/clang_64/lib header/qcustomplot.h -o moc_qcustomplot.cpp

moc_mainwindow.cpp: header/mainwindow.h \
		header/simulation.h \
		../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		header/qcustomplot.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		moc_predefs.h \
		../../../Qt/5.15.2/clang_64/bin/moc
	/Users/nyuad/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/moc_predefs.h -I/Users/nyuad/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/libs/Release -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/header -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/Include -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtSql.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/nyuad/Qt/5.15.2/clang_64/lib header/mainwindow.h -o moc_mainwindow.cpp

moc_worker.cpp: header/worker.h \
		header/simulation.h \
		header/utilities.h \
		../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		moc_predefs.h \
		../../../Qt/5.15.2/clang_64/bin/moc
	/Users/nyuad/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/moc_predefs.h -I/Users/nyuad/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/libs/Release -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/header -I/Users/nyuad/Desktop/Khalil_repos/COVID_sim_app/Include -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtSql.framework/Headers -I/Users/nyuad/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/nyuad/Qt/5.15.2/clang_64/lib header/worker.h -o moc_worker.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.15.2/clang_64/bin/uic \
		header/qcustomplot.h
	/Users/nyuad/Qt/5.15.2/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

